<a href="https://colab.research.google.com/github/ryanaxiom/Applied-ML/blob/main/code/Day07_Carnegie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Student Instructions**: Before you begin, click **File > Save a copy in Drive** so you do not lose your work!

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

print(pd.__version__)
print(np.__version__)

url = ("https://raw.githubusercontent.com/ryanaxiom/Applied-ML/main/data/carnegie_data.csv")

carnegie_raw = pd.read_csv(url, encoding="cp1252")
carnegie = carnegie_raw.copy()
carnegie["research"] = carnegie["serd"] + carnegie["nonserd"]
d = carnegie[carnegie["research"].notna()].copy()
d["med_yn"] = (d["medical"] == 1 ).astype(int)
y = d["research"]

model2 = LinearRegression()
model2.fit(d[["fallenr20","med_yn"]],y)

2.2.3
2.1.3


LinearRegression()

In [ ]:
r2_score(y,model2.predict(d[["fallenr20","med_yn"]]))

0.3193169676075911

In [ ]:
newx = pd.DataFrame({"fallenr20": [11254, 32277], "med_yn": [0,1]})
model2.predict(newx)

array([ 51543.14619529, 528638.10606725])

In [ ]:
model3 = LinearRegression()
model3.fit(d[["fallenr20","med_yn","facnum"]],y)
model3.coef_, model3.intercept_

(array([-1.94289357e+00,  5.26777136e+04,  3.36830193e+02]),
 np.float64(-55169.62746372027))

In [ ]:
r2_score(y,model3.predict(d[["fallenr20","med_yn","facnum"]]))

0.6055276381218307

In [ ]:
model3 = LinearRegression()
model3.fit(d[["fallenr20","med_yn","stem_rsd"]],y)

LinearRegression()

In [ ]:
print(r2_score(y,model3.predict(d[["fallenr20","med_yn","stem_rsd"]])))
model3.coef_, model3.intercept_

0.6261820072600163


(array([-2.47711705e+00,  1.59243152e+05,  2.16899096e+03]),
 np.float64(18342.343102684797))

In [ ]:
pile = ["fallenr20","totdeg","facnum","stem_rsd","med_yn"]

In [ ]:
model5 = LinearRegression()
model5.fit(d[pile],y)

LinearRegression()

In [ ]:
r2_score(y,model5.predict(d[pile]))

0.7410078597023237

In [ ]:
m5pred = model5.predict[d[pile]]
np.sqrt(np.mean((y-m5pred)**2))

TypeError: 'method' object is not subscriptable

In [ ]:
model5.coef_,model5.intercept_

(array([-9.14464032e+00,  1.07459914e+01,  2.28049697e+02,  1.54665696e+03,
         2.48941923e+04]),
 np.float64(-6762.929620374809))

In [ ]:
r2_score(d[["fallenr20"]],d[["totdeg"]])

-0.5893593611581258

In [ ]:
rng = np.random.default_rng(309)
idx = rng.permutation(len(d))
A, B = d.iloc[idx[:151]],d.iloc[idx[151:]]
mA = LinearRegression()
mA.fit(A[pile],A["research"])
mB = LinearRegression()
mB.fit(B[pile],B["research"])

LinearRegression()

In [ ]:
print("model A: ",mA.coef_,mA.intercept_)
print("model B: ",mB.coef_,mB.intercept_)

model A:  [-1.57952651e+01  3.45736703e+01  2.51353825e+02  1.45456897e+03
  6.14960060e+04] -16848.88174203958
model B:  [  -4.18105236   -5.72747914  201.49026698 1501.19505272 4080.20824969] 5638.907524202805


In [ ]:
pile2 = ["fallenr20","facnum","stem_rsd","med_yn"]
rng = np.random.default_rng(309)
idx = rng.permutation(len(d))
A, B = d.iloc[idx[:151]],d.iloc[idx[151:]]
mA = LinearRegression()
mA.fit(A[pile2],A["research"])
mB = LinearRegression()
mB.fit(B[pile2],B["research"])
print("model A: ",mA.coef_,mA.intercept_)
print("model B: ",mB.coef_,mB.intercept_)

model A:  [-7.40251050e+00  2.59562286e+02  1.59599171e+03  6.03450962e+04] -19111.662716257037
model B:  [  -5.46261832  197.43513215 1492.182398   3486.27640067] 5624.309572018421


In [ ]:
np.sqrt(r2_score(mA.predict(d[pile]),mB.predict(d[pile])))

np.float64(0.9676279668122774)

In [ ]:
d[pile].corr().round(2)

,fallenr20,totdeg,facnum,stem_rsd,med_yn
fallenr20,1.00,0.96,0.60,0.62,0.23
totdeg,0.96,1.00,0.67,0.68,0.29
facnum,0.60,0.67,1.00,0.68,0.54
stem_rsd,0.62,0.68,0.68,1.00,0.38
med_yn,0.23,0.29,0.54,0.38,1.00
